export interface RuleDefinition {
  code: string;
  displayName: string;
  ruleType: "objective" | "gray" | "configurable" | "metadata";
  severity: "error" | "warning";
  scope: "invoice" | "invoice_item";
  routeToRole: "legal_ops" | "internal_lawyer";
  description: string;
  hasConfig: boolean;
}

export const RULES_REGISTRY: RuleDefinition[] = [
  {
    code: "RATE_EXCESS",
    displayName: "Rate Excess",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "The charged hourly rate exceeds the maximum approved rate for this timekeeper role and jurisdiction from the applicable rate schedule.",
    hasConfig: false,
  },
  {
    code: "LAWYER_ROLE_MISMATCH",
    displayName: "Role Not Recognised",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "The timekeeper role label on the invoice could not be mapped to any approved role in the rate schedule, preventing a rate check.",
    hasConfig: false,
  },
  {
    code: "RATE_CARD_EXPIRED_OR_MISSING",
    displayName: "Rate Card Missing / Expired",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "No active rate entry was found for this law firm, jurisdiction, and role combination as at the invoice date.",
    hasConfig: false,
  },
  {
    code: "WRONG_CURRENCY",
    displayName: "Wrong Currency",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "The invoice currency does not match the agreed billing currency defined in the Panel T&C or Engagement Letter.",
    hasConfig: false,
  },
  {
    code: "VOLUME_DISCOUNT_NOT_APPLIED",
    displayName: "Volume Discount Not Applied",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "The volume discount threshold has been reached based on cumulative fees for the year, but the applicable discount has not been applied to this invoice.",
    hasConfig: false,
  },
  {
    code: "EXPENSE_CAP_EXCEEDED",
    displayName: "Expense Cap Exceeded",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "An expense line exceeds the maximum reimbursable cap for that expense type as defined in the Panel T&C or Engagement Letter.",
    hasConfig: false,
  },
  {
    code: "FIXED_SCOPE_AMOUNT_MISMATCH",
    displayName: "Fixed Scope Amount Mismatch",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "A Fixed / Closed Scope invoice total exceeds the agreed fixed fee stated in the Engagement Letter.",
    hasConfig: false,
  },
  {
    code: "DUPLICATE_LINE",
    displayName: "Duplicate Line",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "A line item appears to be a duplicate of another line based on identical date, timekeeper, hours, and rate.",
    hasConfig: false,
  },
  {
    code: "ARITHMETIC_ERROR",
    displayName: "Arithmetic Error",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "The line amount does not match the product of hours × rate, indicating a calculation error in the invoice.",
    hasConfig: false,
  },
  {
    code: "BILLING_PERIOD_OUTSIDE_EL",
    displayName: "Billing Outside EL Period",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "One or more line items fall outside the commencement and expiry dates defined in the Engagement Letter.",
    hasConfig: false,
  },
  {
    code: "MISSING_DOCUMENTS_FIXED_SCOPE",
    displayName: "Missing EL (Fixed Scope)",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "A Fixed / Closed Scope invoice has been submitted without an Engagement Letter specifying the agreed fixed fee — a mandatory document.",
    hasConfig: false,
  },
  {
    code: "LINE_ITEMS_IN_FIXED_SCOPE",
    displayName: "Line Items in Fixed Scope",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "A Fixed / Closed Scope invoice contains individual hourly line items, which may indicate an attempt to bill on a time and materials basis.",
    hasConfig: false,
  },
  {
    code: "UNAUTHORIZED_EXPENSE_TYPE",
    displayName: "Unauthorised Expense",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "An expense type was billed that is not on the list of authorised reimbursable expenses under the Panel T&C or Engagement Letter.",
    hasConfig: false,
  },
  {
    code: "TAX_OR_VAT_MISMATCH",
    displayName: "Tax / VAT Mismatch",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "A discrepancy was detected in the tax or VAT amount — incorrect rate, wrong treatment, or arithmetic error in the tax calculation.",
    hasConfig: false,
  },
  {
    code: "INCONSISTENT_RATE_FOR_SAME_TIMEKEEPER",
    displayName: "Inconsistent Rate",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "The same timekeeper appears on multiple lines with different hourly rates within the same invoice, which requires explanation.",
    hasConfig: false,
  },
  {
    code: "DAILY_HOURS_EXCEEDED",
    displayName: "Daily Hours Exceeded",
    ruleType: "objective",
    severity: "error",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "A timekeeper has billed more than the permitted daily cap (default 8 hours) in a single day on this matter without recorded pre-approval.",
    hasConfig: false,
  },
  {
    code: "EL_CONFLICT_WITH_PANEL_BASELINE",
    displayName: "EL / Panel Conflict",
    ruleType: "objective",
    severity: "error",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "The Engagement Letter for this matter contains terms that conflict with the active Panel Rates or Panel T&C, requiring clarification before payment.",
    hasConfig: false,
  },
  {
    code: "HOURS_DISPROPORTIONATE",
    displayName: "Hours Disproportionate",
    ruleType: "gray",
    severity: "warning",
    scope: "invoice_item",
    routeToRole: "internal_lawyer",
    description: "Hours billed by a timekeeper appear disproportionate for the role, task description, or billing period — assessed by AI heuristic.",
    hasConfig: false,
  },
  {
    code: "PARALLEL_BILLING",
    displayName: "Parallel Billing",
    ruleType: "gray",
    severity: "warning",
    scope: "invoice_item",
    routeToRole: "internal_lawyer",
    description: "Multiple timekeepers have billed for similar or overlapping tasks on the same date, suggesting potentially non-billable internal coordination.",
    hasConfig: false,
  },
  {
    code: "SCOPE_CREEP",
    displayName: "Scope Creep",
    ruleType: "gray",
    severity: "warning",
    scope: "invoice_item",
    routeToRole: "internal_lawyer",
    description: "A line item describes work that does not appear to fall within the agreed scope of the Engagement Letter — assessed by AI heuristic.",
    hasConfig: false,
  },
  {
    code: "SENIORITY_OVERKILL",
    displayName: "Seniority Overkill",
    ruleType: "gray",
    severity: "warning",
    scope: "invoice_item",
    routeToRole: "internal_lawyer",
    description: "A task appears routine or administrative in nature but has been assigned to a senior (and therefore expensive) timekeeper — assessed by AI.",
    hasConfig: false,
  },
  {
    code: "ESTIMATE_EXCESS",
    displayName: "Estimate Exceeded",
    ruleType: "gray",
    severity: "warning",
    scope: "invoice",
    routeToRole: "internal_lawyer",
    description: "Cumulative fees for this matter exceed the budget estimate, and no revised estimate or explanation has been provided by the law firm.",
    hasConfig: false,
  },
  {
    code: "INTERNAL_COORDINATION",
    displayName: "Internal Coordination",
    ruleType: "gray",
    severity: "warning",
    scope: "invoice_item",
    routeToRole: "internal_lawyer",
    description: "A line item describes internal team coordination, knowledge transfer, or intra-firm meetings which may not be billable under the T&C.",
    hasConfig: false,
  },
  {
    code: "MEETING_OVERSTAFFING",
    displayName: "Meeting Overstaffing",
    ruleType: "configurable",
    severity: "warning",
    scope: "invoice_item",
    routeToRole: "legal_ops",
    description: "A meeting or call was attended by more timekeepers than the configured maximum threshold, resulting in potentially excessive combined billing.",
    hasConfig: true,
  },
  {
    code: "MISSING_LINE_DETAIL",
    displayName: "Missing Line Detail",
    ruleType: "metadata",
    severity: "warning",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "The invoice does not contain a per-line breakdown with individual dates, hours, and rates — only summary-level information is available.",
    hasConfig: false,
  },
  {
    code: "JURISDICTION_UNCLEAR",
    displayName: "Jurisdiction Unclear",
    ruleType: "metadata",
    severity: "warning",
    scope: "invoice",
    routeToRole: "legal_ops",
    description: "The jurisdiction or applicable law for this invoice could not be determined, preventing accurate application of the jurisdiction-specific rate schedule.",
    hasConfig: false,
  },
];

export const RULE_CODES = RULES_REGISTRY.map(r => r.code);
